project 'SwpKeyChainDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project

  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '9.0'

target 'SwpKeyChainDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SwpKeyChainDemo

  pod 'SwpKeyChain', :path => '../'

end
